project:
  type: website
  output-dir: docs

title: "Estimación de la pose de un vehículo respecto a su estacionamiento en simulación"
date: 06/16/2025
date-format: "MMM, YYYY"
authors:
  - name: Rubén Martínez González
    email: rubenmartinezgonzalez94@gmail.com
    affiliation: "Autor"
  - name: Dr. Arturo Espinosa Romero
    email: eromero@correo.uady.mx
    affiliation: "Asesor"

format:
  revealjs:
    title: "Estimación de la pose de un vehículo respecto a su estacionamiento en simulación"
    subtitle: "Proyecto de tesis"
    bibliography: references.bib
#    header: "Protocolo de tesis"
    footer: Facultad de Matemáticas</br>Universidad Autónoma de Yucatán
    footer-logo-link: "https://www.matematicas.uady.mx"
    theme: moon
    slideNumber: true
    show-slide-number: all
    transition: slide
#    incrementalLists: false
    center: true
    controls: true
    progress: true
    history: true
    logo: /img/uady.svg
    toc: false
    toc-depth: 2
    toc-title: "Contenido"
    toc-icon: "toc"
    code-fold: true
    code-line-numbers: true
    code-line-highlight: true
    sc-sb-title: true
#    incremental: true
css: styles.css
slide-level: 3
number-sections: false

